name: CI hello
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  CI:
    name: Publish hello app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init dagger
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: develop
          workdir: hello
      - name: Test is installed
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          args: -m go functions
          workdir: hello
      - name: Call Dagger Function to build-env
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: build-env
          workdir: hello
      - name: Call Dagger Function to build-env
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: build --source=.
          workdir: hello
      - name: Call Dagger Function to publish
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: publish
          args: --source=.
          workdir: hello
